version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL:-http://localhost:8080}
      - VITE_WEB_URL=${VITE_WEB_URL:-http://localhost:3000}
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ejemplo de API local (opcional)
  # api:
  #   build: ./api  # Si tienes el código del API localmente
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgresql://user:pass@db:5432/mydb
  #   depends_on:
  #     - db

  # Base de datos de ejemplo (opcional)
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_DB=mydb
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=pass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
