version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_WEB_URL=${VITE_WEB_URL}
      - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    
    # Health check para verificar que la aplicación está funcionando
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Si quieres simular también el API localmente
  # api:
  #   image: tu-api-image:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped
